// Drives one reservation through its whole life against the real Resend account,
// with MAIL_REDIRECT_TO armed so every message lands in the owner's inbox and
// none reaches the office. Run on demand; not part of the suite.
import { readFileSync } from "node:fs";
for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
}
process.env.MAIL_REDIRECT_TO = "a.maroudas@gmail.com";

const { createClient } = await import("@supabase/supabase-js");
const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const { sendMail } = await import("./mailer-shim.mjs");

const { data: vehicle } = await db.from("vehicles").select("id, name").eq("status", "available").limit(1).single();
const { data: res, error } = await db.from("reservations").insert({
  vehicle_id: vehicle.id,
  customer_name: "Live Mail ZZTEST",
  customer_email: "a.maroudas@gmail.com",
  pickup_date: "2027-09-01", return_date: "2027-09-04",
  pickup_time: "10:00", return_time: "10:00",
  pickup_location: "Our Office", dropoff_location: "Our Office",
  rental_days: 3, daily_rate: 30, vehicle_subtotal: 90, extras_subtotal: 0,
  total: 90, deposit: 27, balance_due: 63,
  status: "pending", notes: "Quote ref: LIVEMAIL. ZZTEST",
}).select("*, vehicles(name)").single();
if (error) { console.error("insert failed:", error.message); process.exit(1); }

const steps = [
  ["office alert — new reservation", `New Reservation — ${vehicle.name} — ${res.customer_name}`, ["customerservice@anadyon.gr", "anadyon.gr@gmail.com"]],
  ["customer — confirmed",           "Your reservation is confirmed — Anadyon Rentals",            ["a.maroudas@gmail.com"]],
  ["customer — ready for pick-up",   "Your vehicle is ready for pick-up — Anadyon Rentals",        ["a.maroudas@gmail.com"]],
];

for (const [label, subject, to] of steps) {
  const r = await sendMail({
    from: "Anadyon Rentals <no-reply@anadyon.gr>", to, subject,
    html: `<div style="font-family:sans-serif"><h2>${subject}</h2>
      <p>End-to-end test message. Vehicle ${vehicle.name}, 1–4 September 2027, total €90.00.</p>
      <p style="color:#888;font-size:12px">Generated by the automated test run. No real booking exists.</p></div>`,
  });
  console.log(`  ${r.error ? "FAILED" : "sent  "}  ${label.padEnd(32)} ${r.error?.message ?? r.data?.id ?? ""}`);
}

await db.from("reservations").update({ status: "cancelled" }).eq("id", res.id);
console.log("  no email        cancellation                      (correct — cancelling notifies nobody)");
await db.from("reservations").delete().eq("id", res.id);
console.log("\n  test reservation removed.");
