import { readFileSync } from "node:fs";
import { vi } from "vitest";

// Vitest does not read .env.local the way Next does, and these tests talk to the
// real project, so the real keys have to be loaded explicitly.
for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
}

// Nothing generated by this suite may reach ANY inbox.
//
// MAIL_REDIRECT_TO alone was not enough. It kept mail away from the office, but
// it still delivered — and 01-quote.e2e.ts never mocked the mailer, so every
// quote it created sent two real messages, a dozen quotes per run, every run.
// The owner's inbox filled up with hundreds of them.
//
// So the transport itself is stubbed here, for every file in the suite, rather
// than left to each test to remember. lib/mailer.ts imports Resend from this
// module; with it faked, no code path can reach the network however it is
// called. Tests that want to assert on mail still mock "@/lib/mailer" locally
// and capture the calls — that keeps working, and this is the floor beneath it.
//
// tests/e2e/mail-live.mjs is the deliberate exception: it is a separate script,
// run by hand, and does not load this file.
vi.mock("resend", () => ({
  Resend: class {
    emails = {
      send: async () => ({ data: { id: "stubbed-in-tests" }, error: null }),
    };
  },
}));

// Belt and braces: if something ever bypasses the stub, it still cannot reach
// the office, and the key is not a usable credential.
process.env.MAIL_REDIRECT_TO = "blackhole@example.invalid";
process.env.RESEND_API_KEY = "re_test_stub_not_a_real_key";
