import { readFileSync } from "node:fs";

// Vitest does not read .env.local the way Next does, and these tests talk to the
// real project, so the real keys have to be loaded explicitly.
for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
}

// Nothing generated by this suite may reach a real inbox other than the owner's.
process.env.MAIL_REDIRECT_TO = "a.maroudas@gmail.com";
