import { existsSync, readFileSync } from "node:fs";
import { vi } from "vitest";

// Vitest does not load Next's env files. CI supplies process.env; local runs
// may keep staging credentials in .env.staging.local or .env.local.
for (const path of [".env.staging.local", ".env.local"]) {
  if (!existsSync(path)) continue;
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}

// The reset tooling uses staging-prefixed names so production credentials can
// never collide. When they exist, explicitly override the standard names that
// `.env.local` may have populated with production values. CI supplies only the
// standard names, already mapped from staging-specific GitHub secrets.
if (process.env.STAGING_NEXT_PUBLIC_SUPABASE_URL) {
  process.env.NEXT_PUBLIC_SUPABASE_URL =
    process.env.STAGING_NEXT_PUBLIC_SUPABASE_URL;
}
if (process.env.STAGING_NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY =
    process.env.STAGING_NEXT_PUBLIC_SUPABASE_ANON_KEY;
}
if (process.env.STAGING_SUPABASE_SERVICE_ROLE_KEY) {
  process.env.SUPABASE_SERVICE_ROLE_KEY =
    process.env.STAGING_SUPABASE_SERVICE_ROLE_KEY;
}

// A service-role suite is capable of writing anything. It must prove it is
// pointed at the named staging project before any test module constructs a
// client. An explicit flag is intentionally not enough on its own.
const stagingRef = process.env.STAGING_SUPABASE_PROJECT_REF;
const targetUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
if (process.env.E2E_TARGET !== "staging" || !stagingRef || !targetUrl) {
  throw new Error(
    "E2E safety gate: set E2E_TARGET=staging, STAGING_SUPABASE_PROJECT_REF and staging credentials",
  );
}
const target = new URL(targetUrl);
if (target.protocol !== "https:" || target.hostname !== `${stagingRef}.supabase.co`) {
  throw new Error("E2E safety gate: NEXT_PUBLIC_SUPABASE_URL does not match the staging project ref");
}

// Nothing generated by this suite may reach ANY inbox.
//
// MAIL_REDIRECT_TO alone was not enough. It kept mail away from the office, but
// it still delivered — and 01-quote.e2e.ts never mocked the mailer, so every
// quote it created sent two real messages, a dozen quotes per run, every run.
// The owner's inbox filled up with hundreds of them.
//
// So the transport itself is stubbed here, for every file in the suite, rather
// than left to each test to remember. lib/mailer.ts imports Resend from this
// module; with it faked, no code path can reach the network however it is
// called. Tests that want to assert on mail still mock "@/lib/mailer" locally
// and capture the calls — that keeps working, and this is the floor beneath it.
//
// tests/e2e/mail-live.mjs is the deliberate exception: it is a separate script,
// run by hand, and does not load this file.
vi.mock("resend", () => {
  let sent = 0;
  return {
    Resend: class {
      emails = {
        // Provider message ids are unique in reality and the audit table
        // enforces that. A constant fake id made a second successful send look
        // like an application duplicate instead of modelling the provider.
        send: async () => ({
          data: { id: `stubbed-in-tests-${++sent}` },
          error: null,
        }),
      };
    },
  };
});

// Route handlers are usually invoked by Next, which provides the request
// context used by `after()`. These tests call the exported handlers directly,
// so there is no framework request context to keep the background work alive.
// Preserve the production contract in the rig: queue every callback and let
// the test explicitly drain it before cleanup. Running the callback inline
// would make production's post-response work part of the response under test;
// dropping it would leave the booking-email path unexercised altogether.
vi.mock("next/server", async (importOriginal) => {
  const actual = await importOriginal<typeof import("next/server")>();
  return {
    ...actual,
    after: (callback: () => unknown | Promise<unknown>) => {
      const key = Symbol.for("anadyon.e2e.afterTasks");
      const root = globalThis as typeof globalThis & {
        [key]?: Set<Promise<unknown>>;
      };
      const tasks = (root[key] ??= new Set<Promise<unknown>>());
      const task = Promise.resolve().then(callback);
      tasks.add(task);
      void task.then(
        () => tasks.delete(task),
        () => tasks.delete(task),
      );
    },
  };
});

// Belt and braces: if something ever bypasses the stub, it still cannot reach
// the office, and the key is not a usable credential.
process.env.MAIL_REDIRECT_TO = "blackhole@example.invalid";
process.env.RESEND_API_KEY = "re_test_stub_not_a_real_key";
